### ISSUE TITLE
Chromium browser not secure authorization now allowed.

### ISSUE THREAD

**Issue by POCI6996** [NyanHelsing/starfall#2]
The browser it is opening is not considered secure to use to sign in. Is there a bypass or could you make it reference the actual browsers by any chance?

**Comment by NyanHelsing** [comment]
I was able to reproduce this yesterday i think;

It looks like TikTok doesnt like the other login methods; eg fb and google complain.

I have success using the Username and password combo; (not phone number of email).

I can reopen if that doesn't work!

**Comment by POCI6996** [comment]
That was it! Thanks.

Yahoo Mail: Search, Organize, Conquer 
 
  On Mon, May 13, 2024 at 3:14 PM, Joshua ***@***.***> wrote:   


I was able to reproduce this yesterday i think;

It looks like TikTok doesnt like the other login methods; eg fb and google complain.

I have success using the Username and password combo; (not phone number of email).

I can reopen if that doesn't work!
