### ISSUE TITLE
Timeout Errors prevent blocking

### ISSUE THREAD

**Issue by RedSunflowers68** [NyanHelsing/starfall#3]
I ran the script and I am getting consistent time out errors after about 50 tries when it tries to click an element. Attached some screenshots. 
<img width="847" alt="Screenshot 2024-05-16 at 00 16 51" src="https://github.com/NyanHelsing/starfall/assets/78426761/d88b6cd5-41ec-4785-b4ae-dc8f7822c08f">
<img width="871" alt="Screenshot 2024-05-16 at 00 17 05" src="https://github.com/NyanHelsing/starfall/assets/78426761/3b56819c-013a-4ed5-863e-956c504d3ff3">

<img width="818" alt="Screenshot 2024-05-16 at 00 17 42" src="https://github.com/NyanHelsing/starfall/assets/78426761/c702eb71-f6c7-4ab7-9843-00f26f374a38">

**Comment by RedSunflowers68** [comment]
<img width="698" alt="Screenshot 2024-05-16 at 01 19 41" src="https://github.com/NyanHelsing/starfall/assets/78426761/9033bea1-dd10-4e10-9146-00724f10515f">

**Comment by NyanHelsing** [comment]
Interesting so it can't find the ellipses (thats the action button).

If you make the timeout just above that (400) like really long (40000) and see if you're correctly authenticated (should see the pfp in the top right / can see that button/ etc?

Will try to replicate locally

**Comment by NyanHelsing** [comment]
If you do see it; mayb its possible to inspect it and see what the `aria-label` attribute is? it should be `Actions`

<img width="908" alt="Screenshot 2024-05-15 at 8 29 47 PM" src="https://github.com/NyanHelsing/starfall/assets/1523817/26f1f3d7-c4e9-47f4-a380-f1de046c7b02">

**Comment by RedSunflowers68** [comment]
Changing the timeout didn't work, so when I went to see if I could see the button/inspect I realized I couldn't because there was a 'community guidelines' banner blocking it. Never logged into tiktok before on the web so guess I needed to accept their guidelines with the 'got it' button. I honestly didn't even realize it was there until you mentioned I should see the ellipses button. Once I did that I could then see the ellipses and I tried it again and it worked.  Banner was blocking the ellipses button from being found. Sorry that was more me not knowing what the UI was suppose to look like on the web and not paying enough attention to the UI as it ran and more so the terminal. 
Might be worth (if you think it is a good idea) adding that in a troubleshooting section on the READMe or adding in to the script to search for the banner and clicking 'got it' if its there. I only needed to click it once and then it didn't appear ever again.
 
 Photo before I clicked the banner from a video on my phone
![Screenshot_20240516_015411_Studio](https://github.com/NyanHelsing/starfall/assets/78426761/585471bf-aacc-4d25-a95e-c618f31d139a)

Photo after I clicked 'got it' on the banner
<img width="703" alt="Screenshot 2024-05-16 at 01 55 20" src="https://github.com/NyanHelsing/starfall/assets/78426761/35dd3dc7-ccaa-4319-a1cb-29fece291a05">

**Comment by NyanHelsing** [comment]
Ohhhhhhh ! ok yeah that must have been something i clicked and then never saw again; i don't have anything to automate the inputs that result in accepting that


Nice job investigating that i would never have been able to repro that on my account then -_-
